// <auto-generated />
using System;
using Hotel.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.API.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20231031233400_seed_data")]
    partial class seed_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotel.API.Entities.ContactInfo", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelUUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InfoContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoType")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UUID");

                    b.HasIndex("HotelUUID");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            UUID = new Guid("b3d3a8f0-a1ae-4dae-8d9f-40d784bd3701"),
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelUUID = new Guid("db944df0-2aff-4b98-8a1f-f2c9f5266c05"),
                            InfoContent = "0 555 4443322",
                            InfoType = 0,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("c1aa7e25-3381-4bdd-bda7-c84e296b5483"),
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelUUID = new Guid("db944df0-2aff-4b98-8a1f-f2c9f5266c05"),
                            InfoContent = "sunhotel@mail.com",
                            InfoType = 1,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("4b5d54b7-f691-43d7-86f7-cf9cea2168c6"),
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelUUID = new Guid("db944df0-2aff-4b98-8a1f-f2c9f5266c05"),
                            InfoContent = "Antalya",
                            InfoType = 2,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("aaab279f-cc5b-4d65-9da2-a8af1318d72c"),
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelUUID = new Guid("fdc54ea8-9bae-465b-9ab5-e48e55fd9567"),
                            InfoContent = "0 533 5558899",
                            InfoType = 0,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("41a6ed10-888b-4a82-b5f4-60f6475b0a9c"),
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelUUID = new Guid("fdc54ea8-9bae-465b-9ab5-e48e55fd9567"),
                            InfoContent = "moonhotel@mail.com",
                            InfoType = 1,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("da9f948b-e7d3-410a-871c-177a05952335"),
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelUUID = new Guid("e411a7cc-1974-4540-a06e-58dbbc7b0ab4"),
                            InfoContent = "royalhotel@mail.com",
                            InfoType = 1,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hotel.API.Entities.Hotel", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizedFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UUID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            UUID = new Guid("db944df0-2aff-4b98-8a1f-f2c9f5266c05"),
                            AuthorizedFirstName = "Ali",
                            AuthorizedLastName = "Demir",
                            CompanyTitle = "Sun Hotel",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("fdc54ea8-9bae-465b-9ab5-e48e55fd9567"),
                            AuthorizedFirstName = "Veli",
                            AuthorizedLastName = "Öz",
                            CompanyTitle = "Sun Hotel",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UUID = new Guid("e411a7cc-1974-4540-a06e-58dbbc7b0ab4"),
                            AuthorizedFirstName = "Ahmet",
                            AuthorizedLastName = "Duman",
                            CompanyTitle = "Royal Hotel",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hotel.API.Entities.ContactInfo", b =>
                {
                    b.HasOne("Hotel.API.Entities.Hotel", "Hotel")
                        .WithMany("ContactInfos")
                        .HasForeignKey("HotelUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel.API.Entities.Hotel", b =>
                {
                    b.Navigation("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
